"""Add study records and reader preferences.

Revision ID: 4034ef243f18
Revises: 0001_initial
Create Date: 2026-09-01 06:42:04.303355

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4034ef243f18'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reader_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('font_family', sa.String(length=16), nullable=False),
    sa.Column('font_size', sa.Integer(), nullable=False),
    sa.Column('line_height', sa.Integer(), nullable=False),
    sa.Column('column_width', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reader_preference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reader_preference_user_id'), ['user_id'], unique=True)

    op.create_table('annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('selected_text', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_user_id'), ['user_id'], unique=False)

    op.create_table('vocabulary_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vocabulary_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabulary_entry_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocabulary_entry_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_entry_user_id'))
        batch_op.drop_index(batch_op.f('ix_vocabulary_entry_book_id'))

    op.drop_table('vocabulary_entry')
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_user_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_book_id'))

    op.drop_table('annotation')
    with op.batch_alter_table('reader_preference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reader_preference_user_id'))

    op.drop_table('reader_preference')
    # ### end Alembic commands ###
