"""add book content hashes

Revision ID: 6e7c77304567
Revises: 4034ef243f18
Create Date: 2026-09-01 06:53:11.893161

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6e7c77304567'
down_revision = '4034ef243f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_book_content_hash'), ['content_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_content_hash'))
        batch_op.drop_column('content_hash')

    # ### end Alembic commands ###
