"""add epub chapters and anchors

Revision ID: c76f56bbd44a
Revises: 6e7c77304567
Create Date: 2026-09-01 07:10:52.480861

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c76f56bbd44a'
down_revision = '6e7c77304567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_path', sa.String(length=1000), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'ordinal')
    )
    with op.batch_alter_table('book_chapter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_chapter_book_id'), ['book_id'], unique=False)

    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_annotation_chapter_id_book_chapter',
            'book_chapter',
            ['chapter_id'],
            ['id'],
        )

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_root', sa.String(length=64), nullable=True))

    with op.batch_alter_table('vocabulary_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_vocabulary_chapter_id_book_chapter',
            'book_chapter',
            ['chapter_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary_entry', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vocabulary_chapter_id_book_chapter', type_='foreignkey')
        batch_op.drop_column('chapter_id')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('asset_root')

    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_annotation_chapter_id_book_chapter', type_='foreignkey')
        batch_op.drop_column('chapter_id')

    with op.batch_alter_table('book_chapter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_chapter_book_id'))

    op.drop_table('book_chapter')
    # ### end Alembic commands ###
